### PR TITLE
fixing deprecation of unencrypted git protocol for pre-commit repos

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Related to: https://github.com/thoth-station/thoth-application/issues/2111

Should help fix some of the CI issues.

/cc @sallyom

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
will need an approved label to merge.
/cc @quaid
/cc @margarethaley

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
