### PR TITLE
Converting this repo to a Jupyter Book

### PR DESCRIPTION
**Pull request by quaid**

### CODE REVIEW

**Comment by quaid** [comment]
Ah, pre-commit is failing in the toolchain:

> [INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
> An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
> return code: 128
> expected return code: 0
> stdout: (none)
> stderr:
>     fatal: remote error: 
>      The unauthenticated git protocol on port 9418 is no longer supported.
>    Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
>     
> Check the log at /opt/app-root/src/.cache/pre-commit/pre-commit.log

**Comment by quaid** [comment]
OK, I cleared out the cruft to make this a clean PR. Please review and merge.

**Review by schwesig — APPROVED** [review]
/lgtm
/approve

Just on the phone with @quaid

**Pull request merged**
