### PR TITLE
New "Getting Started" section for the website

### PR DESCRIPTION
**Pull request by quaid**

### CODE REVIEW

**Comment by quaid** [comment]
@durandom @schwesig before I manually merge this content into the getting started page, can you confirm if you looked at this content and rejected it on purpose for that page? Or was it an oversight?

**Review by schwesig — APPROVED** [review]
/lgtm
/approve

**Comment by quaid** [comment]
Oops, this content was pulled into the single Getting Started page and this PR is outdated -- it was using the previous way of publishing, for example.

**Pull request closed without merging**
