### PR TITLE
Beginners guide

### LINKED ISSUE #20: Getting started guide for beginners
**Describe what is missing from the handbook**

A document to guide those looking to become contributors who may lack knowledge/experience contributing to open source projects. The guide will provide a few ideas of simpler, more accessible ways to contribute as well as point to helpful resources.

**If you've discovered a solution, would you be willing to contribute it to the handbook?**

I will work on creating this guide for the contributing section of the handbook.

### PR DESCRIPTION
**Pull request by margarethaley**
This pr adds beginners-get-started.md to the contributing folder. The file is intended to provide a few simple ideas for contributing to the handbook, as well as point out to other potentially helpful resources. The purpose of this addition to the handbook is to make contributing more accessible, specifically for anyone who is interested in the work but lacks experience working on open source projects.

Resolves https://github.com/operate-first/community-handbook/issues/20

### CODE REVIEW

**Comment by margarethaley** [comment]
There shouldn't be 3 commits here, I went wrong somewhere with git - i'll work on fixing this

/hold

**Comment by margarethaley** [comment]
Fixed the commits

/unhold

**Review by quaid — COMMENTED** [review]
This is a good framework and key starting content, approve of the links for all of the mysterious GitHub stuff. Making sure people can establish that baseline comfort with the concepts, tools, and processes is going to be something the entire community helps with, continuously. And it all starts here!
/lgtm
/approve

**Pull request merged**
