### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by quaid**
Doing this by what seems like the method here, I added to custom templates and edited them. I'll do this as a PR so we can view the actual changes before commit this time, since it is unclear what is happening.

### CODE REVIEW

**Comment by quaid** [comment]
I'm pretty confused now as to what is supposed to happen, as I think I just followed @margarethaley's pathway.

I'm back to my first guess; Margaret and I can commit files to the repo, but I think we don't have the permission to choose a template for this repo. I bet that is set by role in the overall /operate-first/ project. It may be that someone with the write auth level comes in and chooses the templates we created, for us.

**Comment by tumido** [comment]
> I'm pretty confused now as to what is supposed to happen, as I think I just followed @margarethaley's pathway.
> 
> I'm back to my first guess; Margaret and I can commit files to the repo, but I think we don't have the permission to choose a template for this repo. I bet that is set by role in the overall /operate-first/ project. It may be that someone with the write auth level comes in and chooses the templates we created, for us.

@quaid I'd love to help you, but I'm confused a bit. What's the problem? Which template you're talking about? Issue template or repository template?

1. If issue templates, please know that GitHub doesn't allow you to use an issue template until it's in the master/main.
2. If an repository template - this is selected only when (before) a repository is being created and can't be changed.

**Comment by tumido** [comment]
Oh, I see, you're trying to fix the current issue templates because the issue template chooser screen is not showing them. I admin the preview situation for these files is really sad in GitHub. I think your problem with the original (in `main`) templates is that `labels` (and `assignees) has to be a single string.

```diff
- labels: 'area/contributor', 'kind/handbook'
+ labels: area/contributor, kind/handbook
```

It's just a guess. You probably need to try it out. I think this PR is fixing this exact issue and once merged it should start showing those templates.

Additionally, you can try the new YAML issue templates, which offer a somewhat better control + a preview works for them on GitHub web (even in pull requests)

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Review by margarethaley — APPROVED** [review]
/lgtm

**Comment by margarethaley** [comment]
Seems like this worked!!

Resolves https://github.com/operate-first/community-handbook/issues/6

**Pull request merged**
